version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  price-feed:
    build:
      context: .
      dockerfile: Dockerfile.price-feed
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/arbitragex?authSource=admin
      - REDIS_URI=redis://redis:6379
      - MAINNET_RPC_URL=${MAINNET_RPC_URL}
      - FORK_BLOCK_NUMBER=${FORK_BLOCK_NUMBER}
      - FORK_ENABLED=true
      - UNISWAP_ROUTER_ADDRESS=0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D
      - SUSHISWAP_ROUTER_ADDRESS=0xd9e1cE17f2641f24aE83637ab66a2cca9C378B9F
      - WETH_ADDRESS=0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
      - USDC_ADDRESS=0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48

volumes:
  mongodb_data:
  redis_data:
