version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: arbitragex_mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=arbitragex
    networks:
      - arbitragex_network

  redis:
    image: redis:latest
    container_name: arbitragex_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - arbitragex_network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: arbitragex_api
    ports:
      - '3001:3001'
      - '8080:8080'
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/arbitragex
      - REDIS_HOST=redis
    depends_on:
      - mongodb
      - redis
    networks:
      - arbitragex_network

volumes:
  mongodb_data:
  redis_data:

networks:
  arbitragex_network:
    driver: bridge
